repos:
  - repo: https://github.com/pre-commit/mirrors-semgrep
    rev: v1.27.0
    hooks:
      - id: semgrep
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets-hook